export enum DeliveryStatus {
  REQUESTED = 'REQUESTED',
  PENDING_ASSIGNMENT = 'PENDING_ASSIGNMENT',
  OFFERED = 'OFFERED',
  ASSIGNED = 'ASSIGNED',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  PICKUP_IN_PROGRESS = 'PICKUP_IN_PROGRESS',
  PICKED_UP = 'PICKED_UP',
  ON_THE_WAY = 'ON_THE_WAY',
  ARRIVED = 'ARRIVED',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
